import { Footer } from "./footer";
import { Header } from "./header";

export const metadata = {
  title: "Next.js Tutorial",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
